apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaadin-app-deploy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: vaadin-app
        image: docker.io/kartiksuthar811/vaadin-docker:latest
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: vaadin-app-service
  labels:
    app: web
spec:
  type: NodePort
  
  selector:
    app: web
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
    nodePort: 31243
